<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\SimplCommerce.Infrastructure\SimplCommerce.Infrastructure.csproj" />
    <ProjectReference Include="..\SimplCommerce.Module.Core\SimplCommerce.Module.Core.csproj" />
    <ProjectReference Include="..\SimplCommerce.Module.HangfireJobs\SimplCommerce.Module.HangfireJobs.csproj" />
    <ProjectReference Include="..\SimplCommerce.Module.SignalR\SimplCommerce.Module.SignalR.csproj" />
  </ItemGroup>
</Project>